apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-cxja
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/rsoaresd_org/spi-demos-cgiz-tenant/dotnet-component/devfile-sample-dotnet60-basic-cxja@sha256:942de9f1455d6155b42c1a838684b972d1db684d294a97db604319f103bc122c
        name: main
        resources: {}
status: {}
